GET http://localhost:5005/api/users

###
GET http://localhost:5005/api/users/62ed95a3333559cc1b6dc804

###
POST http://localhost:5005/api/users 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhZWJvdSIsImlkIjoiNjJlYWYyMzQyZDI3MzI0NmE1YWNiNWQyIiwiaWF0IjoxNjU5NTY3Nzk0fQ.gg969Th6nVMWFpeXtCsasfFYFb-Cxmbth1iasiXszIc

{
  "username": "test user",  
  "role": "user",
  "password": "1234567"
}


###
DELETE http://localhost:5005/api/users/62ed95a3333559cc1b6dc804
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhZWJvdSIsImlkIjoiNjJlYWYyMzQyZDI3MzI0NmE1YWNiNWQyIiwiaWF0IjoxNjU5NzM3MTEzfQ.M5en7jYt9bi4lNXA5ezu883_b9-NPoD0aB62msCKRTE

###
PUT http://localhost:5005/api/users/62eaf16a2d273246a5acb5cf
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhZWJvdSIsImlkIjoiNjJlYWYyMzQyZDI3MzI0NmE1YWNiNWQyIiwiaWF0IjoxNjU5NzM0ODk5fQ.AES2oDlYlkdu-NY0l3_7AAopOkAJLmzReyK25lIyGDA

{ 
  "status": "active"
}